pipeline {
    agent any
    stages {
        stage("Build & SonarQube Scanner") {
            agent any
            steps {
                script {
                    withMaven(maven: 'maven') {
                        withSonarQubeEnv('sonarqube') {
                            sh 'mvn clean package sonar:sonar'
                        }
                    }
                }
            }
        }
    }
}
